server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 145792
    url: jdbc:mysql://192.168.137.10:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  application:
    name: gulimall-product
  cloud:
    nacos:
      server-addr: 120.78.10.87:8848
    loadbalancer:
      ribbon:
        enabled: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 配置逻辑删除参数
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.yangjiewei.gulimall: debug
